server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/os?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com:
      jxnu:
        os:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 对应mapper映射xml文件的所在路径
  type-aliases-package: com.jxnu.os.model  # 对应实体类的路径

prop:
  upload-folder: D:/test/

##pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
