server:
  port: 8082
  max-http-header-size: 102400


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.65.18:3306/os?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Homyit17
    password: Homyit.17
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com:
      jxnu:
        os:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 对应mapper映射xml文件的所在路径
  type-aliases-package: com.jxnu.os.model  # 对应实体类的路径

prop:
  upload-folder: D:/test/

##pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
